---
- name: Install Rustup
  block:
    - name: Include OS-specific variables
      ansible.builtin.include_vars: "{{ var_file }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "{{ ansible_lsb.id }}.yml"
      loop_control:
        loop_var: var_file

    - name: Install rustup
      ansible.builtin.include_tasks:
        file: noauto_install_{{ rustup_install_method }}.yml
