---
- name: Add Cargo path script in /etc/profile.d
  ansible.builtin.copy:
    dest: /etc/profile.d/cargo_path.sh
    content: |
      #!/bin/sh
      # Add Cargo bin to the PATH for all users
      if [ -d "$HOME/.cargo/bin" ]; then
          PATH="$HOME/.cargo/bin:$PATH"
      fi
    mode: "0644"
  become: true
