---
- name: Ensure we are using apt
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use apt as a package manager."
  when: ansible_pkg_mgr != "apt"

# NOTE: Rustup package is only available in Debian 13 repositories (which is not yet released). It is therefore installed via installer.
# On Debian-based systems, we have to install rustup from source.
- name: Install rustup from source
  ansible.builtin.include_tasks:
    file: noauto_install_source.yml
