---
- name: Check installed default rust toolchain version
  block:
    - name: Get installed default toolchain version
      ansible.builtin.command:
        cmd: rustc --version
      ignore_errors: true
      changed_when: false
      failed_when: false
      environment:
        PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"
      register: rustup_installed_rust_version_cmd

    - name: Extract only the version into a variable
      ansible.builtin.set_fact:
        rustup_installed_rust_version: "{{ rustup_installed_rust_version_cmd.stdout | regex_replace('^.*?([\\d\\.]{2,}).*$', '\\1') }}"

    - name: Debug installed rust toolchain version
      ansible.builtin.debug:
        var: rustup_installed_rust_version
