---
- name: Ensure rust toolchain is installed
  block:
    - name: Import installed rust toolchain version check
      ansible.builtin.include_tasks: noauto_check_installed_rust_toolchain_version.yml

    - name: Install defined rust toolchain
      when: "rustup_installed_rust_version != rustup_rust_version"
      block:
        - name: Install rust toolchain
          ansible.builtin.command: >
            rustup install {{ rustup_rust_version }}
          environment:
            PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"
          changed_when: true

        - name: Set default rust toolchain
          ansible.builtin.command: >
            rustup default {{ rustup_rust_version }}
          environment:
            PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"
          changed_when: true
