---
- name: Ensure unwanted rust toolchain is uninstalled
  block:
    - name: Import installed rust toolchain version check
      ansible.builtin.include_tasks: noauto_check_installed_rust_toolchain_version.yml

    - name: Uninstall unwanted toolchain
      ansible.builtin.command: >
        rustup uninstall {{ rustup_installed_rust_version }}
      environment:
        PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"
      register: rustup_uninstall_stable_toolchain_cmd
      changed_when: "'uninstalled' in rustup_uninstall_stable_toolchain_cmd.stdout"
      when:
        - rustup_installed_rust_version is defined
        - rustup_installed_rust_version != rustup_rust_version
