---
- name: Verify
  hosts: all
  gather_facts: true
  vars_files:
    - ../../defaults/main.yml

  tasks:
    - name: Check installed rustup version
      ansible.builtin.include_tasks: "../../tasks/noauto_check_installed_version.yml"

    - name: Assert rustup version is correct
      ansible.builtin.assert:
        that:
          - "rustup_installed_version == rustup_version"

    - name: Check installed rust toolchain version
      ansible.builtin.include_tasks: "../../tasks/noauto_check_installed_rust_toolchain_version.yml"

    - name: Assert installed rust version is correct
      ansible.builtin.assert:
        that:
          - "rustup_installed_rust_version == rustup_rust_version"
